version: '3'
services:
    db:
        image: postgres
        restart: always
        env_file:
            - .env
        ports:
            - '5432:5432'
        networks:
            - nest_networks

    api:
        image: nest-js
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        networks:
            - nest_networks

networks:
    nest_networks:
